version: '3.8'
services:
    xmen-challenge:
      image: jhovanny84/reto-xmen
      ports:
        - 8082:8082
      environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/adn_stats_ms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          SPRING_ZIPKIN_BASEURL: http://zipkin
          SPRING_PROFILES_ACTIVE: local
      restart: on-failure
