DROP DATABASE IF EXISTS adn_stats_ms;
DROP USER IF EXISTS `xmen_reto_db`@`%`;
CREATE DATABASE IF NOT EXISTS adn_stats_ms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `xmen_reto_db`@`%` IDENTIFIED WITH mysql_native_password BY 'reto123';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `adn_stats_ms`.* TO `xmen_reto_db`;
